# Specifies the secret data for imagePullSecrets needed to fetch the private docker images
imageCredentials:
  # If aqua-registry already exists in the cluster. Make create to false. So it won't attempt to create a new registry secret. 
  create: true
  name: csp-registry-secret # example
  repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
  registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: ""
  password: ""
  email: "example@gmail.com"

managed: false
environment: aws # aws, acs, onprem

aqua_enable_cache: yes
aqua_cache_expiration_period: 60

image:
  repository: kube-enforcer
  tag: "5.0"
  pullPolicy: Always

nameOverride: "aqua-kube-enforcer"
fullnameOverride: "aqua-kube-enforcer"

namespace: "aqua"

certsSecret:
  name: aqua-kube-enforcer-certs
  serverCertificate: ""
  serverKey: ""

aquaSecret:
  name: aqua-kube-enforcer-token
  kubeEnforcerToken: ""

envs:
  gatewayAddress: csp-gateway-svc:8443 


serviceAccount:
  name: aqua-kube-enforcer-sa

clusterRole:
  name: aqua-kube-enforcer

clusterRoleBinding:
  name: aqua-kube-enforcer  

validatingWebhook:
  name: kube-enforcer-admission-hook-config
  caBundle: ""